print("####### FÓRMULA KI #######")
IC = float(input("Valor de IC50:"))
S = float(input("Concentração do substrato (S):"))
Km = float(input("Constante de Michaelis (KM):"))
print("{0:.3f}".format((IC / (1 + (S/Km)))))
